-- MySQL Script generated by MySQL Workbench
-- Wed Oct 19 13:13:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema workflix
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `workflix` ;

-- -----------------------------------------------------
-- Schema workflix
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `workflix` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `workflix` ;

-- -----------------------------------------------------
-- Table `workflix`.`usuarios_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflix`.`usuarios_clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` CHAR(45) NOT NULL,
  `apellido` CHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(20) NOT NULL,
  `foto_perfil` VARCHAR(2083) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `email_UNIQUE` ON `workflix`.`usuarios_clientes` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `workflix`.`usuarios_profesionales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflix`.`usuarios_profesionales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` CHAR(45) NOT NULL,
  `apellido` CHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(20) NOT NULL,
  `foto_perfil` VARCHAR(2083) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `localidad` CHAR(45) NULL DEFAULT NULL,
  `provincia` CHAR(45) NULL DEFAULT NULL,
  `profesion` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `calificacion_obtenida` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `email_UNIQUE` ON `workflix`.`usuarios_profesionales` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `workflix`.`contrataciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflix`.`contrataciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL DEFAULT NULL,
  `valoracion` FLOAT NULL,
  `comentario` TEXT(200) NULL,
  `id_cliente` INT NOT NULL,
  `id_profesional` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cliente_id`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `workflix`.`usuarios_clientes` (`id`),
  CONSTRAINT `fk_profesional_id`
    FOREIGN KEY (`id_profesional`)
    REFERENCES `workflix`.`usuarios_profesionales` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_cliente_id_idx` ON `workflix`.`contrataciones` (`id_cliente` ASC) VISIBLE;

CREATE INDEX `fk_profesional_id_idx` ON `workflix`.`contrataciones` (`id_profesional` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
